// This file is generated by Slice Machine. Update with care!

import Carousel from './Carousel';
import Clients from './Clients';
import MediaGallery from './MediaGallery';
import Text from './Text';

export {
	Carousel,
	Clients,
	MediaGallery,
	Text,
};

export const components = {
	carousel: Carousel,
	clients: Clients,
	media_gallery: MediaGallery,
	text: Text,
};
